/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  EFX1852P001                            */
/*      FILE         :  stacksct.h                             */
/*      DESCRIPTION  :  Setting of Stack area                  */
/*      CPU SERIES   :  RX200                                  */
/*      CPU TYPE     :  RX210                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/
#pragma stacksize su=0x1000 //200
#pragma stacksize si=0x1000 //300
